# -*- coding: utf-8 -*-
"""dia 3 Marcus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11C4lUKMTPnZNlpquZHYEQ5AvqSlocJex
"""

#Calcule o Índice de Massa Corporal (IMC) usando entradas de peso e altura.

#definindo variáveis e amarrando os possíveis erros:

#ALTURA
while True:
  altura_dig=input("Qual a sua altura abestado?(digite usando PONTO) ")
  try:
    altura=float(altura_dig)
    if altura <= 0:
      print("digite sua altura, você não mede zero!")
      continue
    break
  except:
    print("digite sua altura corretamente abestaiado, USANDO PONTO!!!!!")

#PESO
while True:
  peso_dig=input("Qual o seu peso obeso?(digite somente numeros inteiros) ")
  try:
    peso=int(peso_dig)
    if peso <= 0:
      print("digite seu peso, você não pesa zero!")
      continue
    break
  except:
    print("digite seu peso corretamente chorume!!!!!")

#inserindo o nome pra fazer uma gracinha
nome=input("qual a sua graça desgraça?")

#cálculo do IMC
IMC= peso/(altura**2)

#avaliação de IMC segundo faixas de valores
def avaliacao():
  if IMC < 18.5:
    return "abaixo do peso"
  elif IMC >= 18.5 and IMC <= 24.9:
    return "no peso normal"
  elif IMC >= 25 and IMC <= 29.9:
    return "com sobrepeso"
  elif IMC >= 30 and IMC <= 34.9:
    return "obesidade grau 1"
  elif IMC >= 35 and IMC <= 39.9:
    return "obesidade grau 2"
  else:
    return "obesidade grau 3"

print(f"Olá {nome} belezura bonita demais, o seu IMC é {IMC:.1f} e você está {avaliacao()}")