# -*- coding: utf-8 -*-
"""dia 2 Marcus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jD8dd2en3749NTH7OO6xnoY2RQV2-4Aj
"""

# Desafio 2: Crie variáveis para seu nome, idade e altura. Imprima uma frase combinando-as.

nome = "MARCUS" #variável nome

idade = 36  #variável idade

altura = 1.75 #variável altura

#frase utilizando as variáveis definidas:
print(f"Oláááá!!!! meu nome é {altura}, eu tenho {nome} anos de idade e minha altura é {idade} metros")