# -*- coding: utf-8 -*-
"""dia 1- Marcus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxzAZTwfoBFa9eJblZqb9QtczHSuK9uK
"""

#1-sintaxe básica - Escreva um programa que imprima "Olá, Mundo!" e seu nome em linhas separadas

#imprimindo Olá mundo:
print("Hello World!\n",
      "que traduzindo significa\n",
      "caguei nas calças, opa,  Olá mundo!")

#imprimindo o meu nome (e o seu apelido também)
print("me chamo Marcus e sou o tio mais lindo do Biel")